version: '3.8'
services:
  app:
    image: node:bullseye-slim
    ports: 
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app 
    # entrypoint: npm install
    command: bash -c "npm install && npm run test && tail -f /dev/null"